#ifndef _APP_AWLINK_PROTOCOL_H_
#define _APP_AWLINK_PROTOCOL_H_

#include <stdint.h>

#define PACKED __attribute__((__packed__))

#define AWLINK_VER "v0.1"

#define AWLINK_MAGIC 0xFA

#define AWLINK_IDSRC_MASTER 0
#define AWLINK_IDSRC_CLIENT 1

#define AWLINK_PARSE_STEP_MAGIC		1
#define AWLINK_PARSE_STEP_LENGTH	2
#define AWLINK_PARSE_STEP_ID_SRC	3
#define AWLINK_PARSE_STEP_I_ID		4
#define AWLINK_PARSE_STEP_SI_ID		5
#define AWLINK_PARSE_STEP_DATA		6
#define AWLINK_PARSE_STEP_CHECKSUM1	7
#define AWLINK_PARSE_STEP_CHECKSUM2	8
#define AWLINK_PARSE_STEP_OK		9
#define AWLINK_PARSE_STEP_FAIL		10

#define AWLINK_ACK_OK	0
#define AWLINK_ACK_FAIL	1

#define AWLINK_ITEM_SYSTEM	0
#define AWLINK_ITEM_STATUS	1
#define AWLINK_ITEM_CONTROL	2
#define AWLINK_ITEM_MISSION	3
#define AWLINK_ITEM_PARAM	4
#define AWLINK_ITEM_LOG		5
#define AWLINK_ITEM_FILE	6

#define AWLINK_ITEM_SYSTEM_ACK			0
#define AWLINK_ITEM_SYSTEM_AWLINK_VER	1
#define AWLINK_ITEM_SYSTEM_AWPILOT_VER	2
#define AWLINK_ITEM_SYSTEM_HEART		3
#define AWLINK_ITEM_SYSTEM_MSG			4

#define AWLINK_ITEM_STATUS_BASIC_INFO			0
#define AWLINK_ITEM_STATUS_MISSION_INFO			1
#define AWLINK_ITEM_STATUS_GPS_INFO				2
#define AWLINK_ITEM_STATUS_SENSOR_INFO			3
#define AWLINK_ITEM_STATUS_SENSOR_CALIB_INFO	4
#define AWLINK_ITEM_STATUS_USER1_INFO			5
#define AWLINK_ITEM_STATUS_USER2_INFO			6
#define AWLINK_ITEM_STATUS_USER3_INFO			7
#define AWLINK_ITEM_STATUS_USER4_INFO			8
#define AWLINK_ITEM_STATUS_USER1_NAME_INFO		9
#define AWLINK_ITEM_STATUS_USER2_NAME_INFO		10
#define AWLINK_ITEM_STATUS_USER3_NAME_INFO		11
#define AWLINK_ITEM_STATUS_USER4_NAME_INFO		12
#define AWLINK_ITEM_STATUS_MP_INFO				13
#define AWLINK_ITEM_STATUS_NUM					14
#define AWLINK_ITEM_STATUS_ARUCO_OK				15

#define AWLINK_ITEM_CONTROL_JOYSTICK	0
#define AWLINK_ITEM_CONTROL_STATUS_RATE	1
#define AWLINK_ITEM_CONTROL_CALIBRATE	2
#define AWLINK_ITEM_CONTROL_MODE		3
#define AWLINK_ITEM_CONTROL_FOLLOWME	4
#define AWLINK_ITEM_CONTROL_ATT_OFFSET  5
#define AWLINK_ITEM_CONTROL_MOTOR_TEST	6
#define AWLINK_ITEM_CONTROL_HEADFREE	7
#define AWLINK_ITEM_CONTROL_MISSION		8
#define AWLINK_ITEM_CONTROL_TOF_ALTHOLD 9
#define AWLINK_ITEM_CONTROL_TAKEOFF_ALT 10
#define AWLINK_ITEM_CONTROL_ARUCO_DIST  11

#define AWLINK_ITEM_MISSION_CONTROL		0
#define AWLINK_ITEM_MISSION_GET			1
#define AWLINK_ITEM_MISSION_ITEM		2

#define AWLINK_ITEM_PARAM_CLEAR			0
#define AWLINK_ITEM_PARAM_GET			1
#define AWLINK_ITEM_PARAM_ITEM			2
#define AWLINK_ITEM_PARAM_CONTROL		3

#define AWLINK_ITEM_LOG_GET				0
#define AWLINK_ITEM_LOG_ITEM			1
#define AWLINK_ITEM_LOG_CONTROL			2

#define AWLINK_ITEM_FILE_CONTROL		0
#define AWLINK_ITEM_FILE_ITEM			1
#define AWLINK_ITEM_FILE_STATUS			2

#endif

